/* ============================================================
   Layz - font catalogue
   Each entry: [name, category, tag, bodySafe]
   category : sans | serif | display | handwriting | mono
   tag      : stylistic sub-genre, used by the pairing engine
   bodySafe : 1 = comfortable for long-form body copy
   ============================================================ */
(function (global) {
  'use strict';

  var RAW = [
    /* ---------------- SANS ---------------- */
    ['Inter', 'sans', 'neo-grotesque', 1],
    ['Inter Tight', 'sans', 'neo-grotesque', 1],
    ['Roboto', 'sans', 'neo-grotesque', 1],
    ['Open Sans', 'sans', 'humanist', 1],
    ['Lato', 'sans', 'humanist', 1],
    ['Montserrat', 'sans', 'geometric', 1],
    ['Poppins', 'sans', 'geometric', 1],
    ['Raleway', 'sans', 'geometric', 1],
    ['Nunito', 'sans', 'rounded', 1],
    ['Nunito Sans', 'sans', 'humanist', 1],
    ['Work Sans', 'sans', 'grotesque', 1],
    ['Rubik', 'sans', 'rounded', 1],
    ['Karla', 'sans', 'grotesque', 1],
    ['Manrope', 'sans', 'geometric', 1],
    ['DM Sans', 'sans', 'geometric', 1],
    ['Outfit', 'sans', 'geometric', 1],
    ['Plus Jakarta Sans', 'sans', 'geometric', 1],
    ['Figtree', 'sans', 'geometric', 1],
    ['Sora', 'sans', 'geometric', 1],
    ['Space Grotesk', 'sans', 'grotesque', 1],
    ['Epilogue', 'sans', 'grotesque', 1],
    ['Urbanist', 'sans', 'geometric', 1],
    ['Lexend', 'sans', 'humanist', 1],
    ['Public Sans', 'sans', 'neo-grotesque', 1],
    ['Source Sans 3', 'sans', 'humanist', 1],
    ['IBM Plex Sans', 'sans', 'grotesque', 1],
    ['Barlow', 'sans', 'grotesque', 1],
    ['Cabin', 'sans', 'humanist', 1],
    ['Mulish', 'sans', 'humanist', 1],
    ['Quicksand', 'sans', 'rounded', 1],
    ['Josefin Sans', 'sans', 'geometric', 0],
    ['Archivo', 'sans', 'grotesque', 1],
    ['Archivo Narrow', 'sans', 'condensed', 1],
    ['Asap', 'sans', 'rounded', 1],
    ['Oxygen', 'sans', 'humanist', 1],
    ['Ubuntu', 'sans', 'humanist', 1],
    ['Fira Sans', 'sans', 'humanist', 1],
    ['PT Sans', 'sans', 'humanist', 1],
    ['Noto Sans', 'sans', 'neo-grotesque', 1],
    ['Hind', 'sans', 'humanist', 1],
    ['Heebo', 'sans', 'neo-grotesque', 1],
    ['Assistant', 'sans', 'humanist', 1],
    ['Overpass', 'sans', 'grotesque', 1],
    ['Red Hat Display', 'sans', 'geometric', 1],
    ['Red Hat Text', 'sans', 'geometric', 1],
    ['Chivo', 'sans', 'grotesque', 1],
    ['Commissioner', 'sans', 'humanist', 1],
    ['Onest', 'sans', 'geometric', 1],
    ['Geist', 'sans', 'neo-grotesque', 1],
    ['Instrument Sans', 'sans', 'grotesque', 1],
    ['Bricolage Grotesque', 'sans', 'grotesque', 0],
    ['Schibsted Grotesk', 'sans', 'grotesque', 1],
    ['Albert Sans', 'sans', 'geometric', 1],
    ['Be Vietnam Pro', 'sans', 'geometric', 1],
    ['Familjen Grotesk', 'sans', 'grotesque', 1],
    ['Wix Madefor Display', 'sans', 'grotesque', 1],
    ['Wix Madefor Text', 'sans', 'grotesque', 1],
    ['Jost', 'sans', 'geometric', 1],
    ['Syne', 'sans', 'quirky', 0],
    ['Anek Latin', 'sans', 'humanist', 1],
    ['Gabarito', 'sans', 'rounded', 1],
    ['Hanken Grotesk', 'sans', 'grotesque', 1],
    ['Kumbh Sans', 'sans', 'geometric', 1],
    ['League Spartan', 'sans', 'geometric', 0],
    ['Libre Franklin', 'sans', 'grotesque', 1],
    ['Roboto Condensed', 'sans', 'condensed', 1],
    ['Oswald', 'sans', 'condensed', 0],
    ['Saira', 'sans', 'condensed', 1],
    ['Titillium Web', 'sans', 'grotesque', 1],
    ['Exo 2', 'sans', 'techno', 1],
    ['Cairo', 'sans', 'humanist', 1],
    ['Catamaran', 'sans', 'humanist', 1],
    ['Kanit', 'sans', 'condensed', 0],
    ['Teko', 'sans', 'condensed', 0],
    ['Prompt', 'sans', 'geometric', 1],
    ['Sarabun', 'sans', 'humanist', 1],
    ['Signika', 'sans', 'humanist', 1],
    ['M PLUS Rounded 1c', 'sans', 'rounded', 1],
    ['Rethink Sans', 'sans', 'grotesque', 1],
    ['Darker Grotesque', 'sans', 'condensed', 0],
    ['Antonio', 'sans', 'condensed', 0],
    ['Mukta', 'sans', 'humanist', 1],
    ['Rajdhani', 'sans', 'condensed', 0],
    ['Questrial', 'sans', 'geometric', 1],
    ['Varela Round', 'sans', 'rounded', 1],
    ['Maven Pro', 'sans', 'humanist', 1],
    ['Dosis', 'sans', 'rounded', 0],
    ['Sen', 'sans', 'geometric', 1],
    ['Encode Sans', 'sans', 'grotesque', 1],

    /* ---------------- SERIF ---------------- */
    ['Playfair Display', 'serif', 'didone', 0],
    ['Playfair', 'serif', 'didone', 0],
    ['Merriweather', 'serif', 'transitional', 1],
    ['Lora', 'serif', 'transitional', 1],
    ['PT Serif', 'serif', 'transitional', 1],
    ['Noto Serif', 'serif', 'transitional', 1],
    ['Source Serif 4', 'serif', 'transitional', 1],
    ['Libre Baskerville', 'serif', 'transitional', 1],
    ['Crimson Text', 'serif', 'old-style', 1],
    ['Crimson Pro', 'serif', 'old-style', 1],
    ['EB Garamond', 'serif', 'old-style', 1],
    ['Cormorant Garamond', 'serif', 'old-style', 0],
    ['Cormorant', 'serif', 'old-style', 0],
    ['Spectral', 'serif', 'transitional', 1],
    ['Bitter', 'serif', 'slab', 1],
    ['Domine', 'serif', 'slab', 1],
    ['Arvo', 'serif', 'slab', 1],
    ['Zilla Slab', 'serif', 'slab', 1],
    ['Roboto Slab', 'serif', 'slab', 1],
    ['Josefin Slab', 'serif', 'slab', 0],
    ['Frank Ruhl Libre', 'serif', 'transitional', 1],
    ['Cardo', 'serif', 'old-style', 1],
    ['Neuton', 'serif', 'transitional', 1],
    ['Vollkorn', 'serif', 'old-style', 1],
    ['Alegreya', 'serif', 'old-style', 1],
    ['Literata', 'serif', 'transitional', 1],
    ['Newsreader', 'serif', 'old-style', 1],
    ['Fraunces', 'serif', 'quirky', 0],
    ['Instrument Serif', 'serif', 'didone', 0],
    ['DM Serif Display', 'serif', 'didone', 0],
    ['DM Serif Text', 'serif', 'didone', 1],
    ['Petrona', 'serif', 'transitional', 1],
    ['Gelasio', 'serif', 'transitional', 1],
    ['Bodoni Moda', 'serif', 'didone', 0],
    ['Prata', 'serif', 'didone', 0],
    ['Marcellus', 'serif', 'roman', 0],
    ['Cinzel', 'serif', 'roman', 0],
    ['Eczar', 'serif', 'slab', 0],
    ['Faustina', 'serif', 'transitional', 1],
    ['Lustria', 'serif', 'transitional', 0],
    ['Old Standard TT', 'serif', 'didone', 1],
    ['Sorts Mill Goudy', 'serif', 'old-style', 1],
    ['Tinos', 'serif', 'transitional', 1],
    ['Unna', 'serif', 'didone', 1],
    ['Gloock', 'serif', 'didone', 0],
    ['Young Serif', 'serif', 'slab', 0],
    ['Abril Fatface', 'serif', 'didone', 0],
    ['Yeseva One', 'serif', 'quirky', 0],
    ['Rozha One', 'serif', 'didone', 0],
    ['Libre Caslon Text', 'serif', 'old-style', 1],
    ['Libre Caslon Display', 'serif', 'old-style', 0],
    ['Bree Serif', 'serif', 'slab', 0],
    ['Kaisei Decol', 'serif', 'rounded', 0],
    ['Noticia Text', 'serif', 'transitional', 1],
    ['Rufina', 'serif', 'didone', 0],
    ['Trirong', 'serif', 'transitional', 1],
    ['Suranna', 'serif', 'roman', 0],
    ['Amiri', 'serif', 'old-style', 1],
    ['Kreon', 'serif', 'slab', 1],
    ['Copse', 'serif', 'slab', 0],
    ['Gilda Display', 'serif', 'didone', 0],
    ['Antic Slab', 'serif', 'slab', 0],
    ['Judson', 'serif', 'old-style', 1],

    /* ---------------- DISPLAY ---------------- */
    ['Bebas Neue', 'display', 'condensed', 0],
    ['Anton', 'display', 'condensed', 0],
    ['Archivo Black', 'display', 'grotesque', 0],
    ['Righteous', 'display', 'retro', 0],
    ['Lobster', 'display', 'script-ish', 0],
    ['Pacifico', 'display', 'retro', 0],
    ['Alfa Slab One', 'display', 'slab', 0],
    ['Bungee', 'display', 'blocky', 0],
    ['Bungee Shade', 'display', 'blocky', 0],
    ['Chewy', 'display', 'playful', 0],
    ['Comfortaa', 'display', 'rounded', 0],
    ['Fjalla One', 'display', 'condensed', 0],
    ['Fredoka', 'display', 'rounded', 0],
    ['Monoton', 'display', 'retro', 0],
    ['Orbitron', 'display', 'techno', 0],
    ['Passion One', 'display', 'condensed', 0],
    ['Permanent Marker', 'display', 'marker', 0],
    ['Press Start 2P', 'display', 'pixel', 0],
    ['Russo One', 'display', 'techno', 0],
    ['Shrikhand', 'display', 'retro', 0],
    ['Staatliches', 'display', 'condensed', 0],
    ['Titan One', 'display', 'playful', 0],
    ['Ultra', 'display', 'slab', 0],
    ['Unbounded', 'display', 'quirky', 0],
    ['Vina Sans', 'display', 'condensed', 0],
    ['Rampart One', 'display', 'blocky', 0],
    ['Silkscreen', 'display', 'pixel', 0],
    ['Pixelify Sans', 'display', 'pixel', 0],
    ['Dela Gothic One', 'display', 'blocky', 0],
    ['Lilita One', 'display', 'playful', 0],
    ['Climate Crisis', 'display', 'blocky', 0],
    ['Bowlby One SC', 'display', 'blocky', 0],
    ['Bakbak One', 'display', 'condensed', 0],
    ['Sedgwick Ave', 'display', 'marker', 0],
    ['Bungee Inline', 'display', 'blocky', 0],
    ['Codystar', 'display', 'retro', 0],
    ['Faster One', 'display', 'techno', 0],
    ['Rubik Mono One', 'display', 'blocky', 0],
    ['Rubik Glitch', 'display', 'quirky', 0],
    ['Modak', 'display', 'playful', 0],
    ['Rye', 'display', 'retro', 0],
    ['Sancreek', 'display', 'retro', 0],
    ['Special Elite', 'display', 'typewriter', 0],
    ['Bangers', 'display', 'playful', 0],
    ['Creepster', 'display', 'playful', 0],
    ['Audiowide', 'display', 'techno', 0],
    ['Concert One', 'display', 'playful', 0],
    ['Fugaz One', 'display', 'retro', 0],
    ['Bevan', 'display', 'slab', 0],
    ['Six Caps', 'display', 'condensed', 0],
    ['Julius Sans One', 'display', 'geometric', 0],
    ['Racing Sans One', 'display', 'retro', 0],
    ['Secular One', 'display', 'grotesque', 0],
    ['Yatra One', 'display', 'quirky', 0],
    ['Bungee Outline', 'display', 'blocky', 0],
    ['Tourney', 'display', 'techno', 0],
    ['Bruno Ace', 'display', 'techno', 0],

    /* ---------------- HANDWRITING ---------------- */
    ['Caveat', 'handwriting', 'casual', 0],
    ['Dancing Script', 'handwriting', 'script', 0],
    ['Great Vibes', 'handwriting', 'formal-script', 0],
    ['Indie Flower', 'handwriting', 'casual', 0],
    ['Kalam', 'handwriting', 'casual', 0],
    ['Sacramento', 'handwriting', 'formal-script', 0],
    ['Shadows Into Light', 'handwriting', 'casual', 0],
    ['Amatic SC', 'handwriting', 'condensed', 0],
    ['Architects Daughter', 'handwriting', 'casual', 0],
    ['Patrick Hand', 'handwriting', 'casual', 0],
    ['Gloria Hallelujah', 'handwriting', 'casual', 0],
    ['Homemade Apple', 'handwriting', 'script', 0],
    ['Parisienne', 'handwriting', 'formal-script', 0],
    ['Playball', 'handwriting', 'formal-script', 0],
    ['Rock Salt', 'handwriting', 'marker', 0],
    ['Cookie', 'handwriting', 'formal-script', 0],
    ['Yellowtail', 'handwriting', 'script', 0],
    ['Marck Script', 'handwriting', 'script', 0],
    ['Nothing You Could Do', 'handwriting', 'casual', 0],
    ['La Belle Aurore', 'handwriting', 'casual', 0],
    ['Satisfy', 'handwriting', 'script', 0],
    ['Allura', 'handwriting', 'formal-script', 0],
    ['Bad Script', 'handwriting', 'casual', 0],
    ['Courgette', 'handwriting', 'script', 0],
    ['Kaushan Script', 'handwriting', 'script', 0],
    ['Reenie Beanie', 'handwriting', 'casual', 0],
    ['Just Another Hand', 'handwriting', 'condensed', 0],
    ['Charm', 'handwriting', 'script', 0],
    ['Petit Formal Script', 'handwriting', 'formal-script', 0],

    /* ---------------- MONO ---------------- */
    ['JetBrains Mono', 'mono', 'techno', 1],
    ['Fira Code', 'mono', 'humanist', 1],
    ['IBM Plex Mono', 'mono', 'grotesque', 1],
    ['Source Code Pro', 'mono', 'humanist', 1],
    ['Space Mono', 'mono', 'retro', 0],
    ['Roboto Mono', 'mono', 'neo-grotesque', 1],
    ['Inconsolata', 'mono', 'humanist', 1],
    ['Ubuntu Mono', 'mono', 'humanist', 1],
    ['Courier Prime', 'mono', 'typewriter', 1],
    ['DM Mono', 'mono', 'geometric', 1],
    ['Azeret Mono', 'mono', 'grotesque', 1],
    ['Martian Mono', 'mono', 'techno', 0],
    ['Red Hat Mono', 'mono', 'geometric', 1],
    ['Anonymous Pro', 'mono', 'typewriter', 1],
    ['Cousine', 'mono', 'neo-grotesque', 1],
    ['Overpass Mono', 'mono', 'grotesque', 1],
    ['Noto Sans Mono', 'mono', 'neo-grotesque', 1],
    ['Geist Mono', 'mono', 'neo-grotesque', 1],
    ['Chivo Mono', 'mono', 'grotesque', 1],
    ['Syne Mono', 'mono', 'quirky', 0],
    ['Major Mono Display', 'mono', 'quirky', 0],
    ['Nova Mono', 'mono', 'techno', 0],
    ['Share Tech Mono', 'mono', 'techno', 0],
    ['VT323', 'mono', 'pixel', 0],
    ['Lekton', 'mono', 'humanist', 1],
    ['Spline Sans Mono', 'mono', 'grotesque', 1],
    ['Kode Mono', 'mono', 'techno', 1],
    ['Fragment Mono', 'mono', 'neo-grotesque', 1]
  ];

  function fallbackFor(cat) {
    if (cat === 'serif') return 'Georgia, serif';
    if (cat === 'mono') return 'ui-monospace, monospace';
    if (cat === 'handwriting') return 'cursive';
    if (cat === 'display') return 'system-ui, sans-serif';
    return 'system-ui, -apple-system, sans-serif';
  }

  var FONTS = RAW.map(function (r, i) {
    return {
      name: r[0],
      category: r[1],
      tag: r[2],
      body: !!r[3],
      id: r[0].toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      index: i,
      stack: '"' + r[0] + '", ' + fallbackFor(r[1])
    };
  });

  var BY_NAME = {};
  FONTS.forEach(function (f) { BY_NAME[f.name] = f; });

  var CATEGORIES = [
    { id: 'all', label: 'All' },
    { id: 'sans', label: 'Sans' },
    { id: 'serif', label: 'Serif' },
    { id: 'display', label: 'Display' },
    { id: 'handwriting', label: 'Handwriting' },
    { id: 'mono', label: 'Mono' }
  ];

  /* Hand-picked pairings - the ones worth trusting blindly. */
  var CURATED = [
    ['Playfair Display', 'Source Sans 3', 'Editorial', 'The magazine standard: a high-contrast didone over a calm humanist sans.'],
    ['Instrument Serif', 'Inter', 'Editorial', 'Sharp literary display with the most neutral body text on the web.'],
    ['DM Serif Display', 'DM Sans', 'Superfamily', 'Same studio, same skeleton - contrast without conflict.'],
    ['Fraunces', 'Manrope', 'Quirky', 'Wonky old-style headline cooled down by a geometric sans.'],
    ['Bebas Neue', 'Karla', 'Poster', 'Tall condensed caps over a slightly odd grotesque.'],
    ['Space Grotesk', 'Spectral', 'Reverse', 'Sans headline, serif body - the flipped classic.'],
    ['Cormorant Garamond', 'Lato', 'Luxury', 'Delicate garamond display with a quiet humanist partner.'],
    ['Archivo Black', 'Roboto', 'Brutalist', 'Maximum weight over a workhorse. Zero decoration.'],
    ['Syne', 'Inter Tight', 'Studio', 'Art-directed quirk paired with tight, modern text.'],
    ['Abril Fatface', 'Lora', 'Vintage', 'Fat didone headings above a warm transitional serif.'],
    ['Oswald', 'EB Garamond', 'Newspaper', 'Condensed gothic headline, old-style serif column.'],
    ['Anton', 'Work Sans', 'Impact', 'Heavy statement type with a level-headed grotesque.'],
    ['IBM Plex Sans', 'IBM Plex Mono', 'Technical', 'A superfamily built for documentation and dashboards.'],
    ['Bricolage Grotesque', 'Public Sans', 'Modern', 'Expressive grotesque display, plain-spoken body copy.'],
    ['Prata', 'Nunito Sans', 'Boutique', 'Fashion-house serif softened by a round humanist sans.'],
    ['Sora', 'Merriweather', 'Product', 'Geometric headline, extremely legible reading serif.'],
    ['Unbounded', 'Figtree', 'Playful', 'Wide quirky display with a friendly geometric text face.'],
    ['Cinzel', 'Cardo', 'Classical', 'Roman capitals over an old-style book serif.'],
    ['Caveat', 'Nunito', 'Warm', 'Handwritten accent headings with a rounded, cheerful body.'],
    ['Chivo', 'Newsreader', 'Journal', 'Grotesque headline with a screen-ready reading serif.'],
    ['JetBrains Mono', 'Inter', 'Terminal', 'Monospaced titles for a technical, systems-y voice.'],
    ['Yeseva One', 'Josefin Sans', 'Romantic', 'Curvy display serif with airy geometric text.'],
    ['Red Hat Display', 'Red Hat Text', 'Superfamily', 'Designed as a set - it pairs itself.'],
    ['Alfa Slab One', 'Cabin', 'Retro', 'Fairground slab over a tidy humanist sans.'],
    ['Libre Baskerville', 'Montserrat', 'Trusted', 'Bookish serif above a geometric sans everyone recognises.'],
    ['Young Serif', 'Geist', 'Contemporary', 'Chunky new-school serif with a crisp neutral sans.'],
    ['Bodoni Moda', 'Lato', 'Fashion', 'Extreme stroke contrast, quiet supporting text.'],
    ['Staatliches', 'Rubik', 'Signage', 'Poster caps over a rounded workhorse.'],
    ['Gloock', 'Epilogue', 'Statement', 'Dense didone headline, contemporary grotesque body.'],
    ['Bitter', 'Open Sans', 'Corporate', 'Slab headings with the most reliable sans on the web.']
  ];

  /* Preview samples used across the site */
  var SAMPLES = [
    'The quick brown fox jumps over the lazy dog',
    'Typography is the craft of endowing human language with a durable visual form',
    'Handgloves & Ampersands 0123456789',
    'Design is intelligence made visible',
    'Whereas disregard for good letterforms has resulted'
  ];

  var HEADLINES = [
    ['A quiet revolution in reading', 'Every letterform carries an argument about how a sentence should feel. Choose two that agree, and the page stops fighting the reader. Choose two that disagree politely, and the page starts to sing.'],
    ['The shape of a sentence', 'Good pairings are rarely about contrast for its own sake. They are about hierarchy: one voice announces, the other explains. When both try to announce, nobody listens.'],
    ['Notes on the invisible craft', 'The best typography goes unnoticed. It sets a rhythm, holds a measure, and gets out of the way, leaving only the impression that the writer knew exactly what they were doing.'],
    ['Letters, at scale', 'A typeface behaves differently at fourteen pixels than it does at one hundred and forty. Test your pairing at both extremes before you commit to it, and again on a phone.'],
    ['On restraint', 'Two families are usually enough. Three is a decision you must be prepared to defend. Four is a redesign quietly waiting to happen.']
  ];

  global.LayzData = {
    FONTS: FONTS,
    BY_NAME: BY_NAME,
    CATEGORIES: CATEGORIES,
    CURATED: CURATED,
    SAMPLES: SAMPLES,
    HEADLINES: HEADLINES
  };
})(window);
