/* ============================================================
   Layz - pairings page
   ============================================================ */
(function () {
  'use strict';

  var D = window.LayzData;
  var L = window.Layz;
  var F = window.LayzFonts;
  var P = window.LayzPairs;

  var $ = function (id) { return document.getElementById(id); };

  var current = null;
  var locks = { title: false, body: false };
  var shuffleCount = 0;
  var textEdited = false;

  var el = {
    stage: $('stage'),
    tag: $('pairTag'),
    note: $('pairNote'),
    index: $('pairIndex'),
    eyebrow: $('specEyebrow'),
    title: $('specTitle'),
    deck: $('specDeck'),
    columns: $('specColumns'),
    titleAa: $('titleAa'),
    bodyAa: $('bodyAa'),
    titleName: $('titleName'),
    bodyName: $('bodyName'),
    titleMeta: $('titleMeta'),
    bodyMeta: $('bodyMeta')
  };

  /* ---------------- render ---------------- */
  function applyFonts(pair) {
    var t = pair.title.stack, b = pair.body.stack;

    /* The specimen headline is set at 700, so pull the bold cut too -
       otherwise the preview would quietly lie about the pairing. */
    F.load(pair.title.name, { priority: true, weights: '400;700' });
    el.title.style.fontFamily = t;
    el.titleAa.style.fontFamily = t;
    el.deck.style.fontFamily = b;
    el.columns.style.fontFamily = b;
    el.eyebrow.style.fontFamily = b;
    el.bodyAa.style.fontFamily = b;

    var titleNodes = [el.title, el.titleAa];
    var bodyNodes = [el.deck, el.columns, el.eyebrow, el.bodyAa];
    titleNodes.concat(bodyNodes).forEach(function (n) { n.classList.remove('is-ready'); });

    F.ready(pair.title.name).then(function () {
      titleNodes.forEach(function (n) { n.classList.add('is-ready'); });
    });
    F.ready(pair.body.name).then(function () {
      bodyNodes.forEach(function (n) { n.classList.add('is-ready'); });
    });
  }

  function render(pair, opts) {
    current = pair;
    opts = opts || {};

    el.tag.textContent = pair.label || 'Pairing';
    el.note.textContent = pair.curated
      ? (pair.note || 'Hand-picked pairing')
      : 'Generated by the pairing engine';
    el.index.textContent = 'no. ' + String(++shuffleCount).padStart(3, '0');
    el.eyebrow.textContent = 'Layz / specimen no. ' + String(shuffleCount).padStart(2, '0');

    el.titleName.textContent = pair.title.name;
    el.bodyName.textContent = pair.body.name;
    el.titleMeta.innerHTML = pair.title.category + ' &middot; ' + pair.title.tag;
    el.bodyMeta.innerHTML = pair.body.category + ' &middot; ' + pair.body.tag;
    $('titleInfo').href = 'fonts.html?q=' + encodeURIComponent(pair.title.name);
    $('bodyInfo').href = 'fonts.html?q=' + encodeURIComponent(pair.body.name);

    applyFonts(pair);
    updateCode(pair);
    syncSaveButton();

    if (!opts.silent && !L.reduceMotion) {
      [el.title, el.deck, el.columns].forEach(function (n) {
        n.classList.remove('roll');
        void n.offsetWidth;
        n.classList.add('roll');
      });
    }

    /* keep the URL shareable without adding history entries
       (file:// documents have a null origin and reject replaceState) */
    try {
      history.replaceState(null, '', location.pathname + '?title=' +
        encodeURIComponent(pair.title.name) + '&body=' + encodeURIComponent(pair.body.name));
    } catch (e) { /* running from disk - skip */ }
  }

  function updateCode(pair) {
    $('codeLink').textContent = P.linkFor(pair);
    $('codeCss').textContent = P.cssFor(pair);
  }

  /* ---------------- shuffle ---------------- */
  function shuffle() {
    var pair = P.generate({
      titleCategory: $('titleCat').value,
      bodyCategory: $('bodyCat').value,
      lockTitle: locks.title && current ? current.title.name : null,
      lockBody: locks.body && current ? current.body.name : null
    });
    render(pair);
    el.stage.classList.add('is-rolling');
    setTimeout(function () { el.stage.classList.remove('is-rolling'); }, 400);
  }

  $('shuffleBtn').addEventListener('click', shuffle);
  $('titleCat').addEventListener('change', shuffle);
  $('bodyCat').addEventListener('change', shuffle);

  /* ---------------- locks + swap ---------------- */
  function toggleLock(which) {
    locks[which] = !locks[which];
    var btn = which === 'title' ? $('lockTitle') : $('lockBody');
    btn.setAttribute('aria-pressed', String(locks[which]));
    L.toast((locks[which] ? 'Locked ' : 'Unlocked ') + (which === 'title' ? 'title' : 'text') + ' font');
  }
  $('lockTitle').addEventListener('click', function () { toggleLock('title'); });
  $('lockBody').addEventListener('click', function () { toggleLock('body'); });

  $('swapBtn').addEventListener('click', function () {
    if (!current) { return; }
    render({
      title: current.body,
      body: current.title,
      label: 'Swapped',
      curated: false,
      note: null
    });
  });

  /* ---------------- title scale ---------------- */
  var scale = $('scaleSlider');
  scale.addEventListener('input', function () {
    var v = parseInt(scale.value, 10);
    $('scaleValue').textContent = v + '%';
    /* base must match .spec-title in pairings.css or the first drag jumps */
    el.title.style.fontSize = 'calc(clamp(2.2rem, 6.6vw, 5.2rem) * ' + (v / 100) + ')';
  });

  /* ---------------- sample text ---------------- */
  function setCopy(pick) {
    el.title.textContent = pick[0];
    el.deck.textContent = pick[1].split('. ')[0] + '.';
    el.columns.innerHTML =
      '<p>' + L.escapeHtml(pick[1]) + '</p>' +
      '<p>Test the combination at the sizes you will actually ship. A typeface behaves ' +
      'differently at fourteen pixels than it does at one hundred and forty, and the pair ' +
      'that sang on a poster can mumble in a paragraph.</p>';
  }

  $('newText').addEventListener('click', function () {
    setCopy(D.HEADLINES[Math.floor(Math.random() * D.HEADLINES.length)]);
    textEdited = false;
  });
  $('resetText').addEventListener('click', function () {
    setCopy(D.HEADLINES[0]);
    textEdited = false;
    L.toast('Sample text reset');
  });
  [el.title, el.deck, el.columns].forEach(function (n) {
    n.addEventListener('input', function () { textEdited = true; });
  });

  /* ---------------- save / copy / share ---------------- */
  function asRecord(pair) {
    return { title: pair.title.name, body: pair.body.name, label: pair.label || 'Pairing' };
  }

  function syncSaveButton() {
    if (!current) { return; }
    var on = L.saved.hasPair(asRecord(current));
    $('saveBtn').classList.toggle('is-active', on);
    $('saveLabel').textContent = on ? 'Saved ★' : 'Save';
  }

  $('saveBtn').addEventListener('click', function () {
    if (!current) { return; }
    var added = L.saved.togglePair(asRecord(current));
    syncSaveButton();
    renderSaved();
    L.toast(added ? 'Pairing saved' : 'Pairing removed');
  });

  $('copyBtn').addEventListener('click', function () {
    if (current) { L.copy(P.cssFor(current), 'CSS copied'); }
  });

  $('shareBtn').addEventListener('click', function () {
    L.copy(location.href, 'Link copied');
  });

  document.querySelector('.code-panel').addEventListener('click', function (e) {
    var btn = e.target.closest('[data-copy]');
    if (!btn || !current) { return; }
    var kind = btn.getAttribute('data-copy');
    L.copy(kind === 'link' ? P.linkFor(current) : P.cssFor(current),
      kind === 'link' ? 'Embed tag copied' : 'CSS copied');
  });

  /* ---------------- galleries ---------------- */
  function galleryCard(pair, i, removable) {
    var t = pair.title, b = pair.body;
    return '<button class="gcard" data-title="' + L.escapeHtml(t.name) + '" data-body="' + L.escapeHtml(b.name) + '" ' +
        'data-cursor="Load" style="animation-delay:' + Math.min(i, 14) * 0.03 + 's">' +
      '<span class="gnum num">' + L.pad(i + 1, 2) + '</span>' +
      '<span class="gtitle fnt" data-fnt="' + L.escapeHtml(t.name) + '" style="font-family:' +
        t.stack.replace(/"/g, '&quot;') + '">Aa Bb</span>' +
      '<span class="gbody fnt" data-fnt="' + L.escapeHtml(b.name) + '" style="font-family:' +
        b.stack.replace(/"/g, '&quot;') + '">The quick brown fox jumps over the lazy dog and keeps on running.</span>' +
      '<span class="gfoot">' +
        '<span class="label">' + L.escapeHtml(t.name) + '</span>' +
        '<span class="label label--soft">' + L.escapeHtml(b.name) + '</span>' +
      '</span>' +
      '<span class="gtag label label--soft">' + L.escapeHtml(pair.label || 'Pairing') + '</span>' +
      (removable
        ? '<span class="gremove" data-remove="1" role="button" aria-label="Remove">&times;</span>'
        : '<span class="gremove" aria-hidden="true"></span>') +
    '</button>';
  }

  /* lazy-load the fonts a gallery needs, as it comes into view */
  function watchGallery(container) {
    var io = F.observer(function (node, name) {
      F.ready(name).then(function () { node.classList.add('is-ready'); });
    });
    container.querySelectorAll('.fnt[data-fnt]').forEach(function (n) {
      n.setAttribute('data-font', n.getAttribute('data-fnt'));
      io.observe(n);
    });
  }

  var curated = P.curatedPairs();
  var curatedEl = $('curatedGallery');
  curatedEl.innerHTML = curated.map(function (p, i) { return galleryCard(p, i, false); }).join('');
  watchGallery(curatedEl);

  function renderSaved() {
    var records = L.saved.all().pairs;
    var pairs = records.map(function (r) {
      var t = D.BY_NAME[r.title], b = D.BY_NAME[r.body];
      return (t && b) ? { title: t, body: b, label: r.label } : null;
    }).filter(Boolean);

    $('savedEmpty').hidden = pairs.length > 0;
    $('savedGallery').innerHTML = pairs.map(function (p, i) { return galleryCard(p, i, true); }).join('');
    watchGallery($('savedGallery'));
  }
  renderSaved();

  function galleryClick(e) {
    var card = e.target.closest('.gcard');
    if (!card) { return; }
    var t = D.BY_NAME[card.getAttribute('data-title')];
    var b = D.BY_NAME[card.getAttribute('data-body')];
    if (!t || !b) { return; }

    if (e.target.closest('[data-remove]')) {
      L.saved.removePair({ title: t.name, body: b.name });
      renderSaved();
      syncSaveButton();
      L.toast('Pairing removed');
      return;
    }

    var match = D.CURATED.filter(function (c) { return c[0] === t.name && c[1] === b.name; })[0];
    render({
      title: t, body: b,
      label: match ? match[2] : (card.querySelector('.gtag').textContent || 'Pairing'),
      note: match ? match[3] : null,
      curated: !!match
    });
    window.scrollTo({ top: 0, behavior: L.reduceMotion ? 'auto' : 'smooth' });
  }

  curatedEl.addEventListener('click', galleryClick);
  $('savedGallery').addEventListener('click', galleryClick);

  /* ---------------- keyboard ---------------- */
  document.addEventListener('keydown', function (e) {
    var t = document.activeElement || document.body;
    var typing = /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName) || t.isContentEditable;
    if (typing || e.metaKey || e.ctrlKey || e.altKey) { return; }

    var k = e.key.toLowerCase();
    if (e.code === 'Space') {
      /* let a focused control handle its own Space press */
      if (/^(BUTTON|A|SUMMARY)$/.test(t.tagName)) { return; }
      e.preventDefault();
      shuffle();
      return;
    }
    if (k === 't') { toggleLock('title'); }
    else if (k === 'b') { toggleLock('body'); }
    else if (k === 's') { $('swapBtn').click(); }
    else if (k === 'c') { $('copyBtn').click(); }
    else if (k === 'f') { $('saveBtn').click(); }
  });

  /* ---------------- boot ---------------- */
  (function boot() {
    var qTitle = L.param('title');
    var qBody = L.param('body');
    var t = qTitle && D.BY_NAME[qTitle];
    var b = qBody && D.BY_NAME[qBody];

    if (t && b) {
      var match = D.CURATED.filter(function (c) { return c[0] === t.name && c[1] === b.name; })[0];
      render({ title: t, body: b, label: match ? match[2] : 'Pairing', note: match ? match[3] : null, curated: !!match }, { silent: true });
      return;
    }
    if (t || b) {
      /* one half was requested - lock it and generate the other */
      if (t) { locks.title = true; $('lockTitle').setAttribute('aria-pressed', 'true'); }
      if (b) { locks.body = true; $('lockBody').setAttribute('aria-pressed', 'true'); }
      render(P.generate({ lockTitle: t ? t.name : null, lockBody: b ? b.name : null }), { silent: true });
      return;
    }
    render(P.generate({ curatedChance: 1 }), { silent: true });
  })();
})();
